#controllers:
#    resource: ../../src/Controller/
#    type: annotation

api_rest:
    resource: ../../src/Presentation/Api/Rest/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation